from typing import Any, Dict, List, Optional
from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime, timedelta
import json
import random

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MOCK_COMPANIES = [
    "The Regal Warehousing Services",
    "NADING MECHANICAL, INC.",
    "Crane Equipment & Service of Illinois, Inc.",
    "EMP TECHNICAL GROUP",
    "The Awning Guy",
    "Hotsy Cleaning System",
    "Crossroads Environmental Services"
]

MOCK_INDICATORS = [
    ("Company has all of the required insurance in place", "binary"),
    ("Company has a valid risk assessment for work activities to be carried out", "binary"),
    ("Company confirms that it has all required statutory requirements and permits in place and will comply with all Cummins HSE requirements.", "binary"),
    ("Organisation wants to add comments, relevant information or actions to be implemented related to insurance", "binary"),
    ("Supplier Risk Level (Cummins) - Classification", "binary"),
    ("Total number of people in the undertaking's own workforce", "integer"),
    ("Type of supplier/contractor: Contractor, TPS or TPL", "binary"),
    ("Description of the products and/or services provided to Cummins", "text-long"),
    ("Work and/or delivery of products and services at: a Cummins owned and operated site", "binary"),
    ("For onsite works with Cummins, it is required a permit and/or license to undertake works", "binary"),
    ("Activities undertaken on a Cummins site: Maintenance work", "null"),
    ("Company subcontracts work which has been awarded by Cummins", "binary"),
    ("Company carried out due diligence to ensure that it meets the contractor requirements from Cummins", "binary"),
    ("Number of effective employees working at Cummins sites", "integer"),
    ("Expected revenue per year with Buyer related works", "decimal"),
    ("Contractor company had fatalities in the last two years", "binary"),
    ("Name of the contractor company contact at Cummins", "text-long"),
    ("E-mail of the contractor company contact at Cummins", "text-long"),
    ("Region/country where the undertaking operates: United States", "binary"),
    ("Disclose the position of the undertaking's contact at the buyer", "text"),
    ("Total direct economic value generated by the undertaking", "decimal"),
    ("Value of net revenue", "decimal"),
    ("Renewal date", "binary"),
    ("Type of activities undertaken on a buyers' site: Delivery / Pickup of Goods, Products, or Equipment", "binary")
]

MOCK_REPORTERS = ["Eric Fransen", "April Wolka", "Matt Tharp", "Cory Sulfridge", "James Lucas", "Roger Swezey", "Jordan Mccuen", "John Furiak"]

def generate_mock_data(reporting_period_id: Optional[str] = None) -> List[Dict[str, Any]]:
    data = []
    base_date = datetime.now()
    
    num_records = 20
    if reporting_period_id and reporting_period_id != "all":
        num_records = 12
    
    for i in range(num_records):
        company = random.choice(MOCK_COMPANIES)
        indicator = random.choice(MOCK_INDICATORS)
        reporter = random.choice(MOCK_REPORTERS)
        
        if reporting_period_id and reporting_period_id != "all":
            period_name = reporting_period_id
            custom_period = str(int(reporting_period_id) + 1)
            reported_date = datetime.now() - timedelta(days=random.randint(0, 30))
        else:
            year = 2024
            period_name = str(year)
            custom_period = str(year + 1)
            reported_date = base_date - timedelta(days=random.randint(0, 365))
        
        # Generate appropriate values based on indicator type
        if indicator[1] == "binary":
            if "Classification" in indicator[0]:
                values = ["low", "medium", "high"]
                original_value = random.choice(values)
                formatted_value = ""
            elif "Type of supplier" in indicator[0]:
                values = ["contractor", "third-party-services-contractor-tps", "third-party-logistics-tpl"]
                original_value = random.choice(values)
                formatted_value = original_value
            elif "Renewal" in indicator[0]:
                future_date = reported_date + timedelta(days=365)
                original_value = future_date.strftime("%Y-%m-%d %H:%M:%S")
                formatted_value = ""
            else:
                original_value = random.choice(["yes", "no"])
                formatted_value = original_value
        elif indicator[1] == "integer":
            original_value = str(random.randint(1, 100))
            formatted_value = original_value
        elif indicator[1] == "decimal":
            if "revenue" in indicator[0].lower():
                original_value = f"{random.randint(1, 999)}"
                formatted_value = original_value
            else:
                original_value = str(random.randint(1, 100))
                formatted_value = original_value
        elif indicator[1] == "text-long":
            if "Description" in indicator[0]:
                descriptions = [
                    "We provide HVAC and plumbing contracting services including new installations, repairs, and preventative maintenance.",
                    "Warehousing and shuttle truck service to Cummins. Jamestown Engine Plant-JEP.",
                    "Sales and support of mobile computers, barcode scanners, RFID, and label printers.",
                    "on site awning install & removal",
                    "Supply industrial cleaning equipment (pressure washers, floorcare, parts washers, parts, and detergents)."
                ]
                original_value = random.choice(descriptions)
                formatted_value = original_value
            elif "Name" in indicator[0]:
                names = ["Adam Bailey", "Mike Brooks", "Nick Escalante", "Praveen Radhakrishnan", "JR McKinley", "various"]
                original_value = random.choice(names)
                formatted_value = original_value
            elif "E-mail" in indicator[0]:
                emails = ["adam.bailey@cummins.com", "michael.brooks@cummins.com", "nicholas.escalante@cummins.com", 
                         "praveen.v.radhakrishnan@cummins.com", "john.mckinley@cummins.com", "various"]
                original_value = random.choice(emails)
                formatted_value = original_value
        elif indicator[1] == "text":
            if "position" in indicator[0].lower():
                positions = ["Contractor Safety", "Materials Manager", "IT Leader", "Service Supervisor", "CMEP Facilities Manager", "various"]
                original_value = random.choice(positions)
                formatted_value = original_value
            elif "contact number" in indicator[0].lower():
                original_value = f"{random.randint(100, 999)}-{random.randint(100, 999)}-{random.randint(1000, 9999)}"
                formatted_value = original_value
        elif indicator[1] == "null":
            original_value = "1"
            formatted_value = "1"
        else:
            original_value = "[null]"
            formatted_value = "[null]"
        
        # Format the ISO timestamp
        iso_timestamp = reported_date.strftime("%Y-%m-%dT%H:%M:%S.000000Z")
        
        record = {
            "company_name": company,
            "company_commercial_name": company,
            "indicator_name": indicator[0],
            "indicator_type": indicator[1],
            "reporting_period_name": period_name,
            "reporting_period_custom_name": custom_period,
            "original_value": original_value,
            "formatted_value": formatted_value,
            "reported_at": iso_timestamp,
            "report_type": "granular",
            "origin_of_report": "manual",
            "reported_by": reporter
        }
        data.append(record)
    
    return data

@app.get("/widgets/data_all")
async def get_data_all(reporting_period_id: Optional[str] = Query(None)):
    return generate_mock_data(reporting_period_id)

@app.get("/params/years")
async def get_years():
    years = []
    
    years.append({
        "value": "all",
        "label": "All Periods"
    })
    
    years.append({
        "value": "2024",
        "label": "2024"
    })
    
    years.append({
        "value": "2023",
        "label": "2023"
    })
    
    years.append({
        "value": "2022",
        "label": "2022"
    })
    
    return years

@app.get("/widgets.json")
async def get_widgets():
    with open("widgets.json", "r") as f:
        return json.load(f)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)